export const RPO_CODES = [
  { code: 'A31', description: 'Windows, Power with Driver Express-Down' },
  { code: 'AU3', description: 'Door Locks, Power' },
  { code: 'BTV', description: 'Remote Vehicle Starter System' },
  { code: 'C67', description: 'Air Conditioning, Single-Zone Manual' },
  { code: 'CJ2', description: 'Air Conditioning, Dual-Zone Automatic' },
  { code: 'JL4', description: 'StabiliTrak, Stability Control System' },
  { code: 'K34', description: 'Cruise Control, Electronic with Set and Resume Speed' },
  { code: 'T3U', description: 'Fog Lamps, Front, Halogen' },
  { code: 'T82', description: 'Headlamp Control, Automatic On/Off' },
  { code: 'UD7', description: 'Rear Park Assist, Ultrasonic' },
  { code: 'UQA', description: 'Audio System Feature, Bose Premium 7-Speaker' },
  { code: 'UVC', description: 'Rear Vision Camera' },
  { code: 'V8D', description: 'Vehicle Statement US' },
  { code: 'Z71', description: 'Suspension Package, Off-Road' },
  { code: 'ZQ2', description: 'Driver Convenience Package' },
  { code: 'L33', description: 'Engine: 5.3L V8 Aluminum (Gen III)' },
  { code: 'LM7', description: 'Engine: 5.3L V8 Iron (Gen III)' },
  { code: 'LQ4', description: 'Engine: 6.0L V8 Iron (Gen III)' },
  { code: 'LQ9', description: 'Engine: 6.0L V8 Iron High Output (Gen III)' },
  { code: 'LS1', description: 'Engine: 5.7L V8 Aluminum (Gen III)' },
  { code: 'LS2', description: 'Engine: 6.0L V8 Aluminum (Gen IV)' },
  { code: 'LS3', description: 'Engine: 6.2L V8 Aluminum (Gen IV)' },
  { code: 'LSA', description: 'Engine: 6.2L V8 Supercharged (Gen IV)' },
  { code: 'LS7', description: 'Engine: 7.0L V8 Aluminum (Gen IV)' },
  { code: 'LT1', description: 'Engine: 6.2L V8 Aluminum (Gen V)' },
  { code: 'LT4', description: 'Engine: 6.2L V8 Supercharged (Gen V)' },
  { code: 'M30', description: 'Transmission: 4-Speed Automatic (4L60E)' },
  { code: 'MT1', description: 'Transmission: 4-Speed Automatic Heavy Duty (4L80E)' },
  { code: 'MYC', description: 'Transmission: 6-Speed Automatic (6L80E)' },
  { code: 'MYD', description: 'Transmission: 6-Speed Automatic Heavy Duty (6L90E)' },
  { code: 'M50', description: 'Transmission: 5-Speed Manual (NV3500)' },
  { code: 'MM6', description: 'Transmission: 6-Speed Manual (Borg Warner T56)' },
  { code: 'G80', description: 'Axle: Locking/Limited Slip Differential' },
  { code: 'GU4', description: 'Axle Ratio: 3.08' },
  { code: 'GU5', description: 'Axle Ratio: 3.23' },
  { code: 'GU6', description: 'Axle Ratio: 3.42' },
  { code: 'GT4', description: 'Axle Ratio: 3.73' },
  { code: 'GT5', description: 'Axle Ratio: 4.10' },
  { code: 'HC4', description: 'Axle Ratio: 4.56' },
  { code: 'ZQ8', description: 'Suspension Package, Sport/Handling' },
  { code: 'Z51', description: 'Performance Package, Handling/Brakes' },
  { code: 'FE1', description: 'Suspension System, Soft Ride' },
  { code: 'FE2', description: 'Suspension System, Ride Handling' },
  { code: 'FE3', description: 'Suspension System, Sport' },
  { code: 'FE4', description: 'Suspension System, Special Ride and Handling' },
  { code: 'F41', description: 'Suspension, Firm Ride & Handling' },
  { code: 'J55', description: 'Brake System, Heavy Duty' },
  { code: 'U65', description: 'Audio System, Bose Premium' },
  { code: 'NK3', description: 'Steering Wheel, Leather-Wrapped' },
  { code: 'NP8', description: 'Transfer Case, Auto Active 2-Speed' },
  { code: 'NQH', description: 'Transfer Case, Autotrac 2-Speed' },
  { code: 'NW7', description: 'Traction Control, Electronic' },
  { code: 'PZ3', description: 'Wheels, 18" Chrome-Clad' },
  { code: 'QSS', description: 'Tires, P275/55R20 All-Season' },
  { code: 'V4A', description: 'Bumper, Front Chrome' },
  { code: 'U01', description: 'Lamps, Roof Marker' },
  { code: 'UFL', description: 'Lane Departure Warning' },
  { code: 'K05', description: 'Engine Block Heater' },
  { code: 'K47', description: 'Air Cleaner, High Capacity' },
  { code: 'Z82', description: 'Trailering Equipment Package' }
];
